### ISSUE TITLE
Aggregator goal for generating sources

### ISSUE THREAD

**Issue by eaaltonen** [awhitford/lombok.maven#17]
Related to [SO 29563593](http://stackoverflow.com/questions/29563593/lombok-maven-javadocaggregate-report-with-generated-sources).

I am trying to compile aggregated javadocs for a multimodule Maven project.
The parent project has a packaging of `pom` and it seems like Maven will not run any of the standard goals.

I am proposing to add a goal to lombok-maven-plugin annotated with [@aggregator](http://maven.apache.org/developers/mojo-api-specification.html#The_Descriptor_and_Annotations), which would
* delombok aggregated sources
* add those to the sourcepath

If everything works out as planned, this could then be processed by the maven-javadoc-plugin.

**Comment by awhitford** [comment]
Have you tried configuring `maven-javadoc-plugin` with multiple [`sourcepath`](http://maven.apache.org/plugins/maven-javadoc-plugin/aggregate-mojo.html#sourcepath) values (colon or semi-colon separated)?

**Comment by awhitford** [comment]
I'm unclear what the problem is...  As an example, from the top-level of the `lombok.maven` project (which has 2 modules, one that uses `delombok`), I am able to generate an aggregated javadoc with no special configuration:  `mvn javadoc:aggregate`

I can see that `delombok` is running, and the resulting javadoc contains all classes including the `delombok` code.

**Comment by awhitford** [comment]
I think your problem is related to the fact that `addOutputDirectory` is being set to `false` and `sourceDirectory` is pointing to `src/main/java`.  The `javadoc:aggregate` command is running Delombok, but you can see output:
```
[WARNING] Skipping Delombok; no source to process.
```

**Comment by eaaltonen** [comment]
Thanks for taking a look.
I tried as you suggested and commented out the `lombok-maven-plugin` from the parent. I can see that   delombok runs during the build.

    [INFO] >>> maven-javadoc-plugin:2.10.3:aggregate (default-cli) > generate-sources @ lombok-maven-multimodule >>>
    [INFO]
    [INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    [INFO] Forking lombok-maven-multimodule-lomboklib 0.0.1-SNAPSHOT
    [INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    [INFO]
    [INFO] --- lombok-maven-plugin:1.14.8.0:delombok (delombok) @ lombok-maven-multimodule-lomboklib ---
    [INFO] Delombok complete.
    [INFO]
    [INFO] <<< maven-javadoc-plugin:2.10.3:aggregate (default-cli) < generate-sources @ lombok-maven-multimodule <<<
    [INFO]
    [INFO] --- maven-javadoc-plugin:2.10.3:aggregate (default-cli) @ lombok-maven-multimodule ---

The problem is that for some reason the aggregated javadoc does not actually contain the generated methods.

**Comment by eaaltonen** [comment]
@awhitford What were your results? Were the Lombok generated methods included in the output Javadoc?

**Comment by awhitford** [comment]
The reason why this isn't working for you is because you are running javadoc against the *original source java*, not the *resulting java from delombok*.

The `delombok` goal is designed to transform java code from `src/main/lombok` to `target/generated-source/delombok`.  Then, the other java code found in `src/main/java` is combined with `target/generated-source/delombok` to produce the elaborated javadoc.

**You have to think of delombok as a source code generator.**

By forcing the `delombok` goal to run against `src/main/java` (and disabling the `addOutputDirectory`), the original java source is unchanged, and then javadoc runs only against the original java source.  Now I understand why you need to disable `addOutputDirectory` -- otherwise you will get a *duplicate class* compilation error.

*So how can you get what you really want?*  (Note that Maven has an [addCompileSourceRoot](https://maven.apache.org/ref/3.3.3/apidocs/org/apache/maven/project/MavenProject.html#addCompileSourceRoot(java.lang.String)) method, but not a corresponding *removeCompileSourceRoot*.)  Imagine the following **hack**:
  1. Override the default `<build><sourceDirectory>` from `src/main/java` to be `${project.build.directory}/generated-sources/delombok`.
  2. Override the default delombok `sourceDirectory` from `src/main/lombok` to be `src/main/java`, and disable `addOutputDirectory` (as you have it). 

Basically, you will use `src/main/java`, but Maven will ignore it and instead use `target/generated-sources/delombok`.  The Lombok plugin will transform `src/main/java` into elaborated code in `target/generated-sources/delombok`.  You had step 2, you were just missing step 1.

*Use this hack at your own risk.*  (My guess is that this may confuse your IDE and some other developers.)

```xml
  <build>
    <sourceDirectory>${project.build.directory}/generated-sources/delombok</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok-maven-plugin</artifactId>
        <version>1.16.6.1</version>
        <executions>
          <execution>
            <id>delombok</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>delombok</goal>
            </goals>
            <configuration>
              <addOutputDirectory>false</addOutputDirectory>
              <sourceDirectory>src/main/java</sourceDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
