### ISSUE TITLE
the travis CI is borked for Java 7-9

### ISSUE THREAD

**Issue by pdinc-oss** [awhitford/lombok.maven#38]
```
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "GPL" --cacerts" failed and exited with 3 during .
```

**Comment by awhitford** [comment]
As Ubuntu 14.04 reached EOL on April 30th, 2019, Travis rolled out [changes to make **Xenial** builds the default instead of **Trusty**](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment). Since the `.travis.yml` file does not explicitly set `dist: trusty`, builds are now using Xenial instead of Trusty.

I'm asking _Travis Support_ for clarification on how to get old JDKs with Xenial (or Bionic).  I remain unclear what is wrong with the Travis configuration.

**Comment by awhitford** [comment]
Reverting to *Trusty* has temporarily resolved the issue.  However, since Trusty is EOL, I really want to use Xenial or Bionic (preferably Bionic).  Alas, I can't seem to get JDK 7 & 8 working with anything other than Trusty.  A root issue seems to be that Travis' `install-jdk` script does not like any version prior to 9 anymore:
> Expected feature release number in range of 9 to 14, but got: 8

As a compromise, I'd be open to adjusting the Travis configuration to use Trusty solely for JDK 7 and 8 builds, as long as I can use something newer for the rest.

**Comment by pdinc-oss** [comment]
please go to https://travis-ci.org/awhitford/lombok.maven/builds/576620081 and click the restart build. We cannot cause the build to restart.

**Comment by pdinc-oss** [comment]
Your fix for Travis works.
